const countries = {
  'ar-SA': 'Árabe',
  'bn-IN': 'Bengali',
  'nl-NL': 'holandês',
  'es-ES': 'Espanhol',
  'fr-FR': 'Francês',
  'en-GB': 'Inglês',
  'de-DE': 'alemão',
  'gu-IN': 'Gujarati',
  'hi-IN': 'Hindi',
  'id-ID': 'Indonésio',
  'it-IT': 'italiano',
  'ja-JP': 'Japonês',
  'ko-KR': 'Coreano',
  'kn-IN': 'Kannada',
  'ms-MY': 'Malaio',
  'pt-PT': 'Português PT',
  'pt-BR': 'Português BR',
  'pl-PL': 'Polonês',
  'ru-RU': 'Russo',
  'te-IN': 'Télugo',
  'ta-LK': 'Tâmil',
  'th-TH': 'Tailandês',
  'tr-TR': 'Turco',
  'uk-UA': 'Ucraniano',
  'vi-VN': 'Vietnamita'
}
